# name: Hello World - shell
# description: This action is just for demonstration purposes (or a template), it shows how to execute a shell script in Github action.
name: ðŸ˜» Hello World - shell
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "use ubuntu shell for execute script file or inline code"
        run: |
          echo hello world